### ISSUE TITLE
firebase.ane error, anyone help ?

### ISSUE THREAD

**Issue by kantar35** [distriqt/ANE-Core#15]
<img width="975" alt="Ekran Resmi 2020-12-31 23 32 14" src="https://user-images.githubusercontent.com/3118279/71633545-ccd2ca80-2c25-11ea-9cef-ec6a9fcfb246.png">
Error occurred while packaging the application:

dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:709)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
	at com.android.dx.command.dexer.Main.run(Main.java:245)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
...while parsing com/google/auto/value/extension/memoized/Memoized.class

1 error; aborting

**Comment by SpikeApp** [comment]
If you need support on how to use Spike or solve a specific issue please join our support group at https://www.facebook.com/groups/spikeapp/

We do NOT give one on one support by e-mail.

Thank you!

The Spike Team

**Comment by marchbold** [comment]
Please post support questions for the Firebase ANE in the Firebase repository:

https://github.com/distriqt/ANE-Firebase/issues

That looks like a java version issue though, make sure you have the correct Java version installed.

**Comment by kantar35** [comment]
i had error like this when i build for ios, i am using google sign in ane 03.01.2020, 01:42, "Michael" <notifications@github.com>:Please post support questions for the Firebase ANE in the Firebase repository:https://github.com/distriqt/ANE-Firebase/issuesThat looks like a java version issue though, make sure you have the correct Java version installed.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by marchbold** [comment]
Still would suggest a java version issue, probably a good question for the harman team.
